---
- name: "Apache - Install httpd server"
  yum:
    name: httpd
    state: present
  notify:
    - restart-httpd

- name: "Apache - Install PHP support"
  shell: "amazon-linux-extras install php7.4 -y"
  notify:
    - restart-httpd

- name: "Apache - creating httpd.conf from template"
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart-httpd

- name: "Apache - creating virtualHost"
  template:
    src: virtualhost.conf.j2
    dest: "/var/www/html/{{domain_name}}.conf"
  notify:
    - restart-httpd

- name: "Apache - Creating test.php and test.html"
  copy:
    src: "{{ item }}"
    dest: "/var/www/html/{{ domain_name }}/"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group  }}"
  with_items:
    - test.php
    - test.html
  notify:
    - restart-httpd

- name: "Installing mariaDB"
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: present

- name: "MariaDB server - Restart/ enable service"
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: Create .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400

- name: "setting Root Password"
  mysql_user:
    user: "root"
    host_all: true
    check_implicit_admin: yes
    password: "{{ mariadbroot_pw }}"

- name: "Removes all anonymous user accounts"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadbroot_pw }}"
    name: ""
    host_all: yes
    state: absent

- name: "Delete the test database"
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadbroot_pw }}"
    name: "test"
    state: absent

- name: "Create database"
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadbroot_pw }}"
    name: "{{ db_name }}"
    state: present

- name: "Create databse user"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadbroot_pw }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present

