---
- name: "Wordpress - Downloading Archive File"
  get_url:
    url: "{{ wp_url }}"
    dest: "/tmp/wordpress.tar.gz"
        
- name: "Wordpress - Extracting Archive"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/tmp/"
    remote_src: true
        
- name: "Wordpress - Copying File to DocumentRoot /var/www/html/{{ domain_name }} "
  copy:
    src: "/tmp/wordpress/"
    dest: "/var/www/html/{{ domain_name }}/"
    owner: "{{ httpd_user }}"
    remote_src: true
    group: "{{ httpd_group }}"
        
- name: "Wordpress - Creating wp-config.php"
  template:
    src: wp-config.php.j2
    dest: "/var/www/html/{{ domain_name }}/wp-config.php"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
   
- name: "Post-Installation - Restarting"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - httpd
    - mariadb
